# Generated by Django 5.0.2 on 2024-03-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limonapp', '0002_alter_advertisement_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementattribute',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
