# Generated by Django 5.0.2 on 2024-03-05 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limonapp', '0005_remove_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertise_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='limonapp.advertisestatus'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='attributes',
            field=models.ManyToManyField(null=True, through='limonapp.AdvertisementAttribute', to='limonapp.attribute'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='limonapp.condition'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='limonapp.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
