# Generated by Django 5.0.2 on 2024-03-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limonapp', '0007_remove_advertisement_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='category',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='limonapp.subcategory'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertise_status',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='limonapp.advertisestatus'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='payment_status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='limonapp.paymentstatus'),
        ),
    ]
