# Generated by Django 5.0.2 on 2024-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limonapp', '0008_remove_advertisement_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='attributes',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
