# Generated by Django 5.0.2 on 2024-03-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limonapp', '0009_remove_advertisement_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='attributes',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='attributes',
            field=models.ManyToManyField(null=True, through='limonapp.AdvertisementAttribute', to='limonapp.attribute'),
        ),
    ]
