# Generated by Django 5.0.2 on 2024-03-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limonapp', '0011_remove_advertisement_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
        migrations.DeleteModel(
            name='AdvertisementAttribute',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
