# Generated by Django 5.0.2 on 2024-03-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limonapp', '0013_alter_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='images',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='AdvertiseImage',
        ),
    ]
